/* ============================================
   LearnVerseKids — Configuration
   All app-wide constants and module data
   ============================================ */

export const MODULES = [
  {
    id: 'alphabets',
    name: 'Alphabets',
    icon: '🔤',
    color: '#ff6b9d',
    description: 'Learn A to Z!'
  },
  {
    id: 'numbers',
    name: 'Numbers',
    icon: '🔢',
    color: '#c44dff',
    description: 'Count 1 to 100!'
  },
  {
    id: 'animals',
    name: 'Animals',
    icon: '🦁',
    color: '#ffd84d',
    description: 'Meet the animals!'
  },
  {
    id: 'fruits',
    name: 'Fruits',
    icon: '🍎',
    color: '#51e898',
    description: 'Yummy fruits!'
  },
  {
    id: 'vegetables',
    name: 'Vegetables',
    icon: '🥕',
    color: '#4dc9ff',
    description: 'Healthy veggies!'
  },
  {
    id: 'objects',
    name: 'Objects',
    icon: '🏠',
    color: '#ff884d',
    description: 'Everyday things!'
  }
];

export const ALPHABET_DATA = [
  { letter: 'A', word: 'Apple', emoji: '🍎', color: '#ff4444' },
  { letter: 'B', word: 'Ball', emoji: '⚽', color: '#ff8844' },
  { letter: 'C', word: 'Cat', emoji: '🐱', color: '#ffaa44' },
  { letter: 'D', word: 'Dog', emoji: '🐶', color: '#ffcc44' },
  { letter: 'E', word: 'Elephant', emoji: '🐘', color: '#cccc44' },
  { letter: 'F', word: 'Fish', emoji: '🐟', color: '#88cc44' },
  { letter: 'G', word: 'Grapes', emoji: '🍇', color: '#44cc44' },
  { letter: 'H', word: 'Hat', emoji: '🎩', color: '#44cc88' },
  { letter: 'I', word: 'Ice Cream', emoji: '🍦', color: '#44cccc' },
  { letter: 'J', word: 'Juice', emoji: '🧃', color: '#4488cc' },
  { letter: 'K', word: 'Kite', emoji: '🪁', color: '#4444cc' },
  { letter: 'L', word: 'Lion', emoji: '🦁', color: '#8844cc' },
  { letter: 'M', word: 'Moon', emoji: '🌙', color: '#cc44cc' },
  { letter: 'N', word: 'Nest', emoji: '🪹', color: '#cc4488' },
  { letter: 'O', word: 'Orange', emoji: '🍊', color: '#ff6644' },
  { letter: 'P', word: 'Penguin', emoji: '🐧', color: '#44aaff' },
  { letter: 'Q', word: 'Queen', emoji: '👸', color: '#aa44ff' },
  { letter: 'R', word: 'Rainbow', emoji: '🌈', color: '#ff44aa' },
  { letter: 'S', word: 'Star', emoji: '⭐', color: '#ffdd44' },
  { letter: 'T', word: 'Tree', emoji: '🌳', color: '#44bb44' },
  { letter: 'U', word: 'Umbrella', emoji: '☂️', color: '#4488ff' },
  { letter: 'V', word: 'Violin', emoji: '🎻', color: '#bb8844' },
  { letter: 'W', word: 'Whale', emoji: '🐋', color: '#4466cc' },
  { letter: 'X', word: 'Xylophone', emoji: '🎵', color: '#cc66ff' },
  { letter: 'Y', word: 'Yarn', emoji: '🧶', color: '#ff66aa' },
  { letter: 'Z', word: 'Zebra', emoji: '🦓', color: '#888888' }
];

export const ANIMAL_DATA = [
  { name: 'Lion', emoji: '🦁', color: '#e8a33c', sound: 'Roar!' },
  { name: 'Elephant', emoji: '🐘', color: '#9aa6b2', sound: 'Trumpet!' },
  { name: 'Cat', emoji: '🐱', color: '#ffb366', sound: 'Meow!' },
  { name: 'Dog', emoji: '🐶', color: '#c4874d', sound: 'Woof!' },
  { name: 'Bird', emoji: '🐦', color: '#ff6b6b', sound: 'Tweet!' },
  { name: 'Fish', emoji: '🐟', color: '#4dc9ff', sound: 'Splash!' },
  { name: 'Cow', emoji: '🐮', color: '#f5f5dc', sound: 'Moo!' },
  { name: 'Pig', emoji: '🐷', color: '#ffb6c1', sound: 'Oink!' },
  { name: 'Duck', emoji: '🦆', color: '#ffd84d', sound: 'Quack!' },
  { name: 'Frog', emoji: '🐸', color: '#51e898', sound: 'Ribbit!' },
  { name: 'Monkey', emoji: '🐵', color: '#c4874d', sound: 'Ooh ooh!' },
  { name: 'Bear', emoji: '🐻', color: '#8b6914', sound: 'Growl!' },
  { name: 'Rabbit', emoji: '🐰', color: '#f0e0e0', sound: 'Squeak!' },
  { name: 'Horse', emoji: '🐴', color: '#8b4513', sound: 'Neigh!' },
  { name: 'Butterfly', emoji: '🦋', color: '#c44dff', sound: 'Flutter!' },
  { name: 'Turtle', emoji: '🐢', color: '#228b22', sound: 'Snap!' },
  { name: 'Penguin', emoji: '🐧', color: '#2a2a2a', sound: 'Squawk!' },
  { name: 'Owl', emoji: '🦉', color: '#8b6914', sound: 'Hoot!' },
  { name: 'Bee', emoji: '🐝', color: '#ffd84d', sound: 'Buzz!' },
  { name: 'Shark', emoji: '🦈', color: '#708090', sound: 'Chomp!' },
  { name: 'Tiger', emoji: '🐯', color: '#ff8c00', sound: 'Grrr!' },
  { name: 'Zebra', emoji: '🦓', color: '#333333', sound: 'Bray!' },
  { name: 'Giraffe', emoji: '🦒', color: '#daa520', sound: 'Hum!' },
  { name: 'Crocodile', emoji: '🐊', color: '#2e8b57', sound: 'Snap!' },
  { name: 'Snake', emoji: '🐍', color: '#228b22', sound: 'Hiss!' },
  { name: 'Whale', emoji: '🐋', color: '#4169e1', sound: 'Whoo!' },
  { name: 'Dolphin', emoji: '🐬', color: '#87ceeb', sound: 'Click click!' },
  { name: 'Octopus', emoji: '🐙', color: '#ff6347', sound: 'Squish!' },
  { name: 'Crab', emoji: '🦀', color: '#dc143c', sound: 'Click!' },
  { name: 'Snail', emoji: '🐌', color: '#deb887', sound: 'Slurp!' },
  { name: 'Ant', emoji: '🐜', color: '#8b0000', sound: 'March!' },
  { name: 'Spider', emoji: '🕷️', color: '#2f4f4f', sound: 'Creep!' },
  { name: 'Ladybug', emoji: '🐞', color: '#ff0000', sound: 'Buzz!' },
  { name: 'Scorpion', emoji: '🦂', color: '#d2691e', sound: 'Click!' },
  { name: 'Bat', emoji: '🦇', color: '#4b0082', sound: 'Screech!' },
  { name: 'Hedgehog', emoji: '🦔', color: '#cd853f', sound: 'Snuffle!' },
  { name: 'Squirrel', emoji: '🐿️', color: '#d2691e', sound: 'Chatter!' },
  { name: 'Deer', emoji: '🦌', color: '#8b4513', sound: 'Bleat!' },
  { name: 'Fox', emoji: '🦊', color: '#ff6600', sound: 'Yap!' },
  { name: 'Wolf', emoji: '🐺', color: '#696969', sound: 'Howl!' },
  { name: 'Gorilla', emoji: '🦍', color: '#555555', sound: 'Hoo hoo!' },
  { name: 'Koala', emoji: '🐨', color: '#a9a9a9', sound: 'Grunt!' },
  { name: 'Panda', emoji: '🐼', color: '#f5f5f5', sound: 'Munch!' },
  { name: 'Kangaroo', emoji: '🦘', color: '#cd853f', sound: 'Boing!' },
  { name: 'Llama', emoji: '🦙', color: '#f5deb3', sound: 'Hum!' },
  { name: 'Parrot', emoji: '🦜', color: '#00ff00', sound: 'Squawk!' },
  { name: 'Flamingo', emoji: '🦩', color: '#ff69b4', sound: 'Honk!' },
  { name: 'Eagle', emoji: '🦅', color: '#8b4513', sound: 'Screech!' },
  { name: 'Peacock', emoji: '🦚', color: '#008080', sound: 'Call!' },
  { name: 'Swan', emoji: '🦢', color: '#ffffff', sound: 'Honk!' },
  { name: 'Rooster', emoji: '🐓', color: '#ff4500', sound: 'Cock-a-doodle!' },
  { name: 'Chick', emoji: '🐥', color: '#ffd700', sound: 'Cheep!' },
  { name: 'Mouse', emoji: '🐭', color: '#d3d3d3', sound: 'Squeak!' },
  { name: 'Hamster', emoji: '🐹', color: '#f4a460', sound: 'Squeak!' },
  { name: 'Sheep', emoji: '🐑', color: '#f0f0f0', sound: 'Baa!' },
  { name: 'Goat', emoji: '🐐', color: '#deb887', sound: 'Meh!' },
  { name: 'Camel', emoji: '🐪', color: '#d2b48c', sound: 'Grunt!' },
  { name: 'Hippo', emoji: '🦛', color: '#778899', sound: 'Snort!' },
  { name: 'Rhino', emoji: '🦏', color: '#808080', sound: 'Snort!' },
  { name: 'Leopard', emoji: '🐆', color: '#daa520', sound: 'Growl!' },
  { name: 'Dragon', emoji: '🐉', color: '#228b22', sound: 'Roar!' },
  { name: 'Unicorn', emoji: '🦄', color: '#ff69b4', sound: 'Neigh!' },
  { name: 'T-Rex', emoji: '🦖', color: '#556b2f', sound: 'ROAR!' },
  { name: 'Mammoth', emoji: '🦣', color: '#8b4513', sound: 'Trumpet!' },
  { name: 'Dodo', emoji: '🦤', color: '#a0522d', sound: 'Coo!' }
];

export const FRUIT_DATA = [
  { name: 'Apple', emoji: '🍎', color: '#ff4444' },
  { name: 'Banana', emoji: '🍌', color: '#ffe135' },
  { name: 'Orange', emoji: '🍊', color: '#ff8c00' },
  { name: 'Grapes', emoji: '🍇', color: '#8b008b' },
  { name: 'Strawberry', emoji: '🍓', color: '#ff355e' },
  { name: 'Watermelon', emoji: '🍉', color: '#23c48e' },
  { name: 'Peach', emoji: '🍑', color: '#ffb07c' },
  { name: 'Pineapple', emoji: '🍍', color: '#ffd700' },
  { name: 'Cherry', emoji: '🍒', color: '#de3163' },
  { name: 'Lemon', emoji: '🍋', color: '#fff44f' },
  { name: 'Mango', emoji: '🥭', color: '#ff8243' },
  { name: 'Coconut', emoji: '🥥', color: '#8b4513' },
  { name: 'Blueberry', emoji: '🫐', color: '#4169e1' },
  { name: 'Kiwi', emoji: '🥝', color: '#7cfc00' },
  { name: 'Pear', emoji: '🍐', color: '#d1e231' },
  { name: 'Avocado', emoji: '🥑', color: '#568203' },
  { name: 'Melon', emoji: '🍈', color: '#98fb98' },
  { name: 'Plum', emoji: '🫐', color: '#8e4585' },
  { name: 'Fig', emoji: '🫒', color: '#5d3a1a' },
  { name: 'Guava', emoji: '🍈', color: '#a8e61d' },
  { name: 'Papaya', emoji: '🍈', color: '#ffa500' },
  { name: 'Pomegranate', emoji: '🍎', color: '#c41e3a' },
  { name: 'Dragonfruit', emoji: '🍈', color: '#ff1493' },
  { name: 'Lychee', emoji: '🍒', color: '#ff6b6b' },
  { name: 'Jackfruit', emoji: '🍈', color: '#ffc107' },
  { name: 'Tangerine', emoji: '🍊', color: '#ff9966' },
  { name: 'Lime', emoji: '🍋', color: '#32cd32' },
  { name: 'Apricot', emoji: '🍑', color: '#fbceb1' },
  { name: 'Cranberry', emoji: '🍒', color: '#9b111e' },
  { name: 'Raspberry', emoji: '🍒', color: '#e30b5c' },
  { name: 'Blackberry', emoji: '🫐', color: '#3b0066' },
  { name: 'Starfruit', emoji: '⭐', color: '#ffd700' },
  { name: 'Passion Fruit', emoji: '🍇', color: '#7b2d8b' },
  { name: 'Durian', emoji: '🍈', color: '#9acd32' },
  { name: 'Nectarine', emoji: '🍑', color: '#ff6347' }
];

export const VEGETABLE_DATA = [
  { name: 'Carrot', emoji: '🥕', color: '#ff8c00' },
  { name: 'Broccoli', emoji: '🥦', color: '#228b22' },
  { name: 'Corn', emoji: '🌽', color: '#ffd700' },
  { name: 'Tomato', emoji: '🍅', color: '#ff4444' },
  { name: 'Potato', emoji: '🥔', color: '#c4a35a' },
  { name: 'Onion', emoji: '🧅', color: '#deb887' },
  { name: 'Pepper', emoji: '🫑', color: '#32cd32' },
  { name: 'Mushroom', emoji: '🍄', color: '#cd853f' },
  { name: 'Cucumber', emoji: '🥒', color: '#008b45' },
  { name: 'Eggplant', emoji: '🍆', color: '#800080' },
  { name: 'Lettuce', emoji: '🥬', color: '#00ff7f' },
  { name: 'Garlic', emoji: '🧄', color: '#f5f5dc' },
  { name: 'Peas', emoji: '🫛', color: '#2e8b57' },
  { name: 'Sweet Potato', emoji: '🍠', color: '#ff6347' },
  { name: 'Hot Pepper', emoji: '🌶️', color: '#ff0000' },
  { name: 'Spinach', emoji: '🥬', color: '#006400' },
  { name: 'Cabbage', emoji: '🥬', color: '#90ee90' },
  { name: 'Cauliflower', emoji: '🥦', color: '#fffdd0' },
  { name: 'Radish', emoji: '🥕', color: '#ff355e' },
  { name: 'Beetroot', emoji: '🥕', color: '#8b0000' },
  { name: 'Celery', emoji: '🥬', color: '#7cfc00' },
  { name: 'Zucchini', emoji: '🥒', color: '#3cb371' },
  { name: 'Pumpkin', emoji: '🎃', color: '#ff7518' },
  { name: 'Asparagus', emoji: '🥦', color: '#87a96b' },
  { name: 'Turnip', emoji: '🥕', color: '#f0e68c' },
  { name: 'Artichoke', emoji: '🥦', color: '#558b2f' },
  { name: 'Leek', emoji: '🥬', color: '#66bb6a' },
  { name: 'Okra', emoji: '🥒', color: '#6b8e23' },
  { name: 'Ginger', emoji: '🧄', color: '#d2b48c' },
  { name: 'Parsley', emoji: '🌿', color: '#228b22' },
  { name: 'Basil', emoji: '🌿', color: '#006400' },
  { name: 'Mint', emoji: '🌿', color: '#00ff7f' },
  { name: 'Kale', emoji: '🥬', color: '#355e3b' },
  { name: 'Bean Sprout', emoji: '🌱', color: '#98fb98' },
  { name: 'Green Bean', emoji: '🫛', color: '#228b22' },
  { name: 'Brussels Sprout', emoji: '🥬', color: '#556b2f' },
  { name: 'Bell Pepper', emoji: '🫑', color: '#ff4500' },
  { name: 'Jalapeño', emoji: '🌶️', color: '#008000' },
  { name: 'Watercress', emoji: '🌿', color: '#2e8b57' },
  { name: 'Spring Onion', emoji: '🧅', color: '#32cd32' },
  { name: 'Fennel', emoji: '🌿', color: '#9acd32' },
  { name: 'Yam', emoji: '🍠', color: '#cd853f' },
  { name: 'Butternut', emoji: '🎃', color: '#deb887' },
  { name: 'Arugula', emoji: '🥬', color: '#3cb371' },
  { name: 'Chive', emoji: '🌿', color: '#66cdaa' },
  { name: 'Chard', emoji: '🥬', color: '#b22222' },
  { name: 'Endive', emoji: '🥬', color: '#f0fff0' },
  { name: 'Taro', emoji: '🥔', color: '#9370db' },
  { name: 'Lotus Root', emoji: '🥕', color: '#f5deb3' },
  { name: 'Bamboo Shoot', emoji: '🌱', color: '#daa520' }
];

export const OBJECT_DATA = [
  { name: 'House', emoji: '🏠', color: '#ff884d' },
  { name: 'Car', emoji: '🚗', color: '#ff4444' },
  { name: 'Book', emoji: '📖', color: '#4dc9ff' },
  { name: 'Ball', emoji: '⚽', color: '#ffffff' },
  { name: 'Clock', emoji: '🕐', color: '#ffd84d' },
  { name: 'Phone', emoji: '📱', color: '#333333' },
  { name: 'Chair', emoji: '🪑', color: '#8b4513' },
  { name: 'Cup', emoji: '☕', color: '#f5f5dc' },
  { name: 'Key', emoji: '🔑', color: '#ffd700' },
  { name: 'Shoe', emoji: '👟', color: '#ff6b6b' },
  { name: 'Hat', emoji: '🎩', color: '#2a2a2a' },
  { name: 'Bag', emoji: '🎒', color: '#ff884d' },
  { name: 'Pencil', emoji: '✏️', color: '#ffd84d' },
  { name: 'Star', emoji: '⭐', color: '#ffd84d' },
  { name: 'Heart', emoji: '❤️', color: '#ff4444' },
  { name: 'Sun', emoji: '☀️', color: '#ffd700' },
  { name: 'Moon', emoji: '🌙', color: '#ffd84d' },
  { name: 'Rainbow', emoji: '🌈', color: '#ff6b9d' },
  { name: 'Flower', emoji: '🌸', color: '#ffb6c1' },
  { name: 'Bicycle', emoji: '🚲', color: '#4dc9ff' },
  { name: 'Airplane', emoji: '✈️', color: '#87ceeb' },
  { name: 'Train', emoji: '🚂', color: '#708090' },
  { name: 'Boat', emoji: '⛵', color: '#1e90ff' },
  { name: 'Rocket', emoji: '🚀', color: '#ff6347' },
  { name: 'Guitar', emoji: '🎸', color: '#d2691e' },
  { name: 'Piano', emoji: '🎹', color: '#1a1a1a' },
  { name: 'Drum', emoji: '🥁', color: '#cd853f' },
  { name: 'Trumpet', emoji: '🎺', color: '#ffd700' },
  { name: 'Camera', emoji: '📷', color: '#555555' },
  { name: 'Television', emoji: '📺', color: '#333333' },
  { name: 'Computer', emoji: '💻', color: '#c0c0c0' },
  { name: 'Lamp', emoji: '💡', color: '#ffd700' },
  { name: 'Scissors', emoji: '✂️', color: '#c0c0c0' },
  { name: 'Paintbrush', emoji: '🖌️', color: '#4169e1' },
  { name: 'Crayon', emoji: '🖍️', color: '#ff6347' },
  { name: 'Globe', emoji: '🌍', color: '#1e90ff' },
  { name: 'Compass', emoji: '🧭', color: '#b22222' },
  { name: 'Map', emoji: '🗺️', color: '#f5deb3' },
  { name: 'Telescope', emoji: '🔭', color: '#4682b4' },
  { name: 'Microscope', emoji: '🔬', color: '#708090' },
  { name: 'Magnet', emoji: '🧲', color: '#ff0000' },
  { name: 'Battery', emoji: '🔋', color: '#228b22' },
  { name: 'Wrench', emoji: '🔧', color: '#808080' },
  { name: 'Hammer', emoji: '🔨', color: '#8b4513' },
  { name: 'Shield', emoji: '🛡️', color: '#4682b4' },
  { name: 'Crown', emoji: '👑', color: '#ffd700' },
  { name: 'Ring', emoji: '💍', color: '#ffd700' },
  { name: 'Diamond', emoji: '💎', color: '#00bfff' },
  { name: 'Gift', emoji: '🎁', color: '#ff4444' },
  { name: 'Balloon', emoji: '🎈', color: '#ff355e' },
  { name: 'Candle', emoji: '🕯️', color: '#ffd700' },
  { name: 'Bell', emoji: '🔔', color: '#ffd700' },
  { name: 'Umbrella', emoji: '☂️', color: '#4169e1' },
  { name: 'Tent', emoji: '⛺', color: '#228b22' },
  { name: 'Ladder', emoji: '🪜', color: '#8b4513' },
  { name: 'Pillow', emoji: '🛏️', color: '#e6e6fa' },
  { name: 'Mirror', emoji: '🪞', color: '#c0c0c0' },
  { name: 'Toothbrush', emoji: '🪥', color: '#00bfff' },
  { name: 'Soap', emoji: '🧼', color: '#e0ffff' },
  { name: 'Towel', emoji: '🧴', color: '#dda0dd' },
  { name: 'Broom', emoji: '🧹', color: '#deb887' },
  { name: 'Backpack', emoji: '🎒', color: '#4169e1' },
  { name: 'Notebook', emoji: '📓', color: '#ff69b4' },
  { name: 'Ruler', emoji: '📏', color: '#deb887' },
  { name: 'Magnifier', emoji: '🔍', color: '#c0c0c0' },
  { name: 'Lock', emoji: '🔒', color: '#ffd700' },
  { name: 'Anchor', emoji: '⚓', color: '#4682b4' },
  { name: 'Wheel', emoji: '☸️', color: '#696969' },
  { name: 'Dice', emoji: '🎲', color: '#ffffff' },
  { name: 'Trophy', emoji: '🏆', color: '#ffd700' },
  { name: 'Medal', emoji: '🏅', color: '#ffd700' },
  { name: 'Kite', emoji: '🪁', color: '#ff6b9d' },
  { name: 'Puzzle', emoji: '🧩', color: '#4dc9ff' },
  { name: 'Robot', emoji: '🤖', color: '#c0c0c0' },
  { name: 'Teddy Bear', emoji: '🧸', color: '#d2691e' }
];

export const THEMES = [
  { id: 'rainbow', icon: '🌈', name: 'Rainbow' },
  { id: 'space', icon: '🚀', name: 'Space' },
  { id: 'ocean', icon: '🌊', name: 'Ocean' },
  { id: 'forest', icon: '🌲', name: 'Forest' }
];

// Difficulty settings — bigger for kids to see
export const DIFFICULTY = {
  slow: {
    objectScale: 1.6,
    floatSpeed: 0.3,
    hitRadius: 2.0,
    spawnDelay: 400,
    promptDuration: 4000
  },
  normal: {
    objectScale: 1.3,
    floatSpeed: 0.5,
    hitRadius: 1.6,
    spawnDelay: 300,
    promptDuration: 2500
  }
};

// Number names for TTS
export const NUMBER_WORDS = [
  '', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten',
  'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen', 'Twenty',
  'Twenty-One', 'Twenty-Two', 'Twenty-Three', 'Twenty-Four', 'Twenty-Five', 'Twenty-Six', 'Twenty-Seven', 'Twenty-Eight', 'Twenty-Nine', 'Thirty',
  'Thirty-One', 'Thirty-Two', 'Thirty-Three', 'Thirty-Four', 'Thirty-Five', 'Thirty-Six', 'Thirty-Seven', 'Thirty-Eight', 'Thirty-Nine', 'Forty',
  'Forty-One', 'Forty-Two', 'Forty-Three', 'Forty-Four', 'Forty-Five', 'Forty-Six', 'Forty-Seven', 'Forty-Eight', 'Forty-Nine', 'Fifty',
  'Fifty-One', 'Fifty-Two', 'Fifty-Three', 'Fifty-Four', 'Fifty-Five', 'Fifty-Six', 'Fifty-Seven', 'Fifty-Eight', 'Fifty-Nine', 'Sixty',
  'Sixty-One', 'Sixty-Two', 'Sixty-Three', 'Sixty-Four', 'Sixty-Five', 'Sixty-Six', 'Sixty-Seven', 'Sixty-Eight', 'Sixty-Nine', 'Seventy',
  'Seventy-One', 'Seventy-Two', 'Seventy-Three', 'Seventy-Four', 'Seventy-Five', 'Seventy-Six', 'Seventy-Seven', 'Seventy-Eight', 'Seventy-Nine', 'Eighty',
  'Eighty-One', 'Eighty-Two', 'Eighty-Three', 'Eighty-Four', 'Eighty-Five', 'Eighty-Six', 'Eighty-Seven', 'Eighty-Eight', 'Eighty-Nine', 'Ninety',
  'Ninety-One', 'Ninety-Two', 'Ninety-Three', 'Ninety-Four', 'Ninety-Five', 'Ninety-Six', 'Ninety-Seven', 'Ninety-Eight', 'Ninety-Nine', 'One Hundred'
];
